### ISSUE TITLE
Socket problems..

### ISSUE THREAD

**Issue by Emixam23** [rdavisau/sockets-for-pcl#143]
I don't get it, my friend and I are developing an API and our WebSocket services works, but not the mobile side.. I tried with a couple of clients, on the web, our `echo` messaging and everything works.

The thing is, I mean, the things seem like the socket is mono-directional. I tried your example:

    var address = "127.0.0.1";
    var port = 11000;
    var r = new Random(); 
    
    var client = new TcpSocketClient();
    await client.ConnectAsync(address, port);
    
    // we're connected!
    for (int i = 0; i<5; i++)
    {
        // write to the 'WriteStream' property of the socket client to send data
        var nextByte = (byte) r.Next(0,254);
        client.WriteStream.WriteByte(nextByte);
        await client.WriteStream.FlushAsync();
      
        // wait a little before sending the next bit of data
        await Task.Delay(TimeSpan.FromMilliseconds(500)); 
    }
    
    await client.DisconnectAsync();

First, after I get connected with this :

    public async void ConnectSocketToAPIAsync()
        {
            SocketClient = new TcpSocketClient();
            await SocketClient.ConnectAsync("my.ws.service", 4242);
            ActiveSocketExchange();
        }

        public async void ActiveSocketExchange()
        {
            var bytesRead = -1;
            var buf = new byte[1];

            while (bytesRead != 0)
            {
                bytesRead = await SocketClient.ReadStream.ReadAsync(buf, 0, 1);
                if (bytesRead > 0)
                    MessagingCenter.Send((App)Current, SOCKET_Message, System.Text.Encoding.UTF8.GetString(buf, 0, bytesRead));
            }
        }

Everything's fine, my TcpClient is well initialized (even the web-link becomes the http's API addr)

From my page view, when I'm done writing my text, I'm pressing the done button of the keyboard and this code is called:

    private void InitSocketPart()
        {
            MessagingCenter.Subscribe<App, string>((App)Application.Current, App.SOCKET_Message, (sender, text) =>
            {
                SocketResponseText = text;
            });
        }

        private async void OnTextCompleted(object sender, EventArgs ea)
        {
            var bytes = Encoding.UTF8.GetBytes(TextToSend);
            try {
                if (App.SocketClient.WriteStream.CanRead)
                    Debug.WriteLine("canRead");
                if (App.SocketClient.WriteStream.CanWrite)
                    Debug.WriteLine("canWrite");
                
                App.SocketClient.WriteStream.Write(bytes, 0, TextToSend.Length);
                App.SocketClient.WriteStream.Flush();
            } catch (Exception e)
            {
                Debug.WriteLine(e);
            }
        }

So now CanWrite && CanRead are true, but nothing at all happens, even with the use of `Async` methods... Why so? I don't get it..

*The use of messaging center is just to have only one point of incoming message*. I'm using it for other things and it works perfectly :)

Thank for any help..

**Comment by rdavisau** [comment]
Howdy,

I don't know a lot about websockets; I thought that to connect to them from a raw TCP socket you would need to implement the WSS protocol yourself - am I mistaken?

From reading the sample I'm not 100% clear exactly what you mean to do, but some tips that might be helpful -

* For a more realistic socket communication sample you should check here: https://github.com/rdavisau/sockets-for-pcl/blob/dev/Sockets/linqpad-samples/Tcp/Strings.linq If you have LINQPad, you can install sockets-for-pcl and run it from there. It demonstrates sending and receiving with a basic protocol. I recommend implementing a protocol so that you can buffer larger reads. 

* You should replace the `async void` methods with `async Task` and ensure you `await` at the root of the call chain, as it may be masking exceptions. 

Let me know if this helps or if you have more questions

**Comment by Emixam23** [comment]
Hi,

Alright, I will test, but sockets must be directionals? doesn't it?

Thanks

**Comment by rdavisau** [comment]
Yes, the sockets are bi-directional 👍

**Comment by Emixam23** [comment]
So this piece of code should work doesn't?

    public class TCPClient
    {
        TcpSocketClient client = new TcpSocketClient();
        private string server_ip { get; set; }
        private int port { get; set; }
        private bool connected;

        #region Constructors
        public TCPClient()
        {
            server_ip = "";
            port = 0;
            connected = false;
        }

        public TCPClient(string server_ip, int port)
        {
            this.server_ip = server_ip;
            this.port = port;
            connected = false;
            Connect();
        }
        #endregion Constructors

        #region Send & Receive
        public async Task<string> ReceiveString(Action<string> callback)
        {
            // get the length of the next message
            var sizeOfInt = sizeof(Int32);
            var sizeBuf = new byte[sizeOfInt];

            await client.ReadStream
                   .ReadAsync(sizeBuf, 0, sizeOfInt)
                   .ConfigureAwait(false);

            // convert to int
            var msgLength = BitConverter.ToInt32(sizeBuf, 0);

            // get the actual message
            var msgBuf = new byte[msgLength];
            await client.ReadStream
                   .ReadAsync(msgBuf, 0, msgLength)
                   .ConfigureAwait(false);

            // convert to string
            var msg = Encoding.UTF8.GetString(msgBuf, 0, msgLength);
            Debug.WriteLine(msg);

            return msg;
        }

        public Task SendString(string s)
        {
            // convert to utf8 bytes
            var msgBytes = Encoding.UTF8.GetBytes(s);
            var msgLength = msgBytes.Length;
            var msgLengthBytes = BitConverter.GetBytes(msgLength);

            // prepare the bytes to send
            var allBytes = Enumerable.Concat(msgLengthBytes, msgBytes).ToArray();

            // send 
            return client.WriteStream.WriteAsync(allBytes, 0, allBytes.Length);
        }
        #endregion Send & Receive

        #region Connection/Disconnection handling
        public async void Connect()
        {
            await client.ConnectAsync(this.server_ip, this.port);
            connected = true;
        }
        public async void Connect(string server_ip, string port)
        {
            await client.ConnectAsync(server_ip, port);
            connected = true;
        }

        public async void Disconnect()
        {
            await client.DisconnectAsync();
            connected = false;
        }

        public bool IsConnected() { return this.connected; }
        public bool IsDisconnected() { return !this.connected; }

        #endregion Connection/Disconnection handling
        }
    }

I init() it and using it like that:

    #region Attributes
        public static readonly BindableProperty TextToSendProperty =
            BindableProperty.Create(nameof(TextToSend), typeof(string), typeof(GroupPage), null);

        public string TextToSend
        {
            get { return (string)GetValue(TextToSendProperty); }
            set { SetValue(TextToSendProperty, value); }
        }

        public static readonly BindableProperty SocketResponseTextProperty =
            BindableProperty.Create(nameof(SocketResponseText), typeof(string), typeof(GroupPage), null);

        public string SocketResponseText
        {
            get { return (string)GetValue(SocketResponseTextProperty); }
            set { SetValue(SocketResponseTextProperty, value); }
        }
        #endregion

        public TCPClient SocketClient { get; private set; }

        private void InitSocketPart()
        {
            SocketClient = new TCPClient("my.api.fr", 8047);
            SocketClient.Connect();
        }

        private void OnTextCompleted(object sender, EventArgs ea)
        {
            if (SocketClient.IsConnected())
            {
                SocketClient.SendString(TextToSend);
                SocketClient.ReceiveString((string s) =>
                {
                    SocketResponseText = s;
                });
            }
        }

If I'm right and if I understand what you've told me and the link you gave me, then it should work? It seems to be a lot of code but it's just an encapsulation of yours with a sample example how to use it ;)

To me, it should works, but idk.. I feel like I miss something but what?

Thanks !

**PS/Edit 1**: I'm testing on a echo server

**Comment by rdavisau** [comment]
Howdy, thanks for posting more code, it gives some hints.

As I mentioned before you need to get rid of the `async void`. This may not be the only problem with the code but will probably mask errors. 

For example, there is a logic error in the code - in `InitSocketPart`, you use your host and port constructor overload, which then calls the `Connect` method without awaiting it. Since that call is not awaited, your code will proceed immediately whether or not the connection has been made. Of course, you can't await a constructor, so this kind of work is not suited to a constructor. You could try some of the approaches mentioned in the page I link at the end. 

The error is compounded then, as immediately after `Connect` is called by `InitSocketPart` once more - again without awaiting. However, it is invalid to ask a socket that is already connected, or in the process of connecting, to connect. If you have your debugger set to catch thrown exceptions you'll probably see an exception depending on the state (connected or still trying to connect), for example:

![image](https://user-images.githubusercontent.com/7392704/32812110-07914d04-c9ef-11e7-804a-cf060b0e7eb7.png)

But since this code is also not awaited, everything proceeds and the exceptions are probably lost in the ether somewhere.

With these two issues, it's not clear whether the program is in a valid state after those things occur, so it would be best to address those issues and first and see how you go. 

There's some old but good reference material on async/await here that might help https://blog.stephencleary.com/2013/01/async-oop-0-introduction.html

**Comment by Emixam23** [comment]
Wow, thank you so much, I can't work on it now but tonight I will for sure ! thank I'll come back to you asap :)

**Comment by rdavisau** [comment]
No problems, I can't say for sure that this will solve all the problems but I'm confident we can get it working 😎7

**Comment by Emixam23** [comment]
I'm checking right now, you know what? I feel like my send and my receive are just wrong :O it's like I'm mixing UDP and TCP. Also, maybe I'm lost, maybe your package doesn't handle WebSockets because, maybe, it's just a different process/thing?

**Comment by rdavisau** [comment]
Yes, you are possibly right. I was thinking earlier that unless I misunderstood everything, for websockets you might need to implement the protocol yourself which is not time well spent. I haven't used it myself, but for portable websockets you might try https://github.com/NVentimiglia/Websockets.PCL

**Comment by Emixam23** [comment]
Hi,

Yeah I tried with this package and it does work... I am so stupid sometimes...

Thank for alll the time you spent to help me :)

**Comment by rdavisau** [comment]
No problems 👍
