### ISSUE TITLE
String Read and Write

### ISSUE THREAD

**Issue by NVentimiglia** [rdavisau/sockets-for-pcl#15]
I am converting a Windows8 websocket client to Xamarin and need PCL support. I found this project, but the implementation is very different from the MessageWebSocket.

Can the documentation be updated to demonstrate the reading and writing of string messages ? I noticed there was a helper project, but, It requires using a json format which my server will not support.

**Comment by rdavisau** [comment]
Hi,

As you would have gathered, sockets just shuffle bytes back and forward. In order to send and receive strings you need to implement a basic protocol that both sides can follow in order to communicate (here is the extensive [websocket](http://datatracker.ietf.org/doc/rfc6455/?include_text=1) protocol!). For strings, the two most popular options are: 
* terminate each message with a delimiter
* precede each message with its length. 

I'm a fan of the second option. I've outlined them both in [here](https://github.com/rdavisau/sockets-for-pcl/issues/6#issuecomment-73841797) in issue #6, that should be enough to get you going. 

At some stage I may add documentation to cover cases like this, but in the meantime, these are just plain sockets so there is plenty out there on the net if you want to read further. The helper project will definitely add a `StringMessenger`-like class in the future.

**Comment by rdavisau** [comment]
Putting together some samples for LINQPad, here's an implementation of the string protocol as extension methods on `ITcpSocketClient`. You can use `SendStringAsync` and `ReceiveStringAsync` to send and receive string messages up to Int32.MaxValue length. 
```csharp
// Implements a basic string reading/writing protocol
// bytes 1 - sizeof(int32) 	: message length
// subsequent bytes			: message
public static class StringHelpers
{
	public static async Task<string> ReceiveStringAsync(this ITcpSocketClient c)
	{
		// get the length of the next message
		var sizeOfInt = sizeof(Int32);
		var sizeBuf = new byte[sizeOfInt];
		
		await c.ReadStream
			   .ReadAsync(sizeBuf, 0, sizeOfInt)
			   .ConfigureAwait(false);
		
		var msgLength = BitConverter.ToInt32(sizeBuf, 0);
		
		// get the actual message
		var msgBuf = new byte[msgLength];
		await c.ReadStream
			   .ReadAsync(msgBuf, 0, msgLength)
			   .ConfigureAwait(false);

		// convert to string
		var msg = Encoding.UTF8.GetString(msgBuf, 0, msgLength);
		
		return msg;
	}
	
	public static Task SendStringAsync(this ITcpSocketClient c, string s)
	{
		// convert to utf8 bytes
		var msgBytes = Encoding.UTF8.GetBytes(s);
		var msgLength = msgBytes.Length;
		var msgLengthBytes = BitConverter.GetBytes(msgLength);
		
		// prepare the bytes to send
		var allBytes = Enumerable.Concat(msgLengthBytes, msgBytes).ToArray();
		
		// send 
		return c.WriteStream.WriteAsync(allBytes, 0, allBytes.Length);				
	}
}
```
