### ISSUE TITLE
Websockets for PCL

### ISSUE THREAD

**Issue by NVentimiglia** [rdavisau/sockets-for-pcl#17]
Over the weekend I utilized sockets-for-pcl in conjunction with Websockets.Portable to create a pcl compliant websocket implementation.

https://github.com/NVentimiglia/WebSocket.Portable

It is in it's early stages, but works so far. You are invited to take a look. Also, if anyone is in need of a pcl websocket a forward would be nice.

**Comment by rdavisau** [comment]
Cool - good stuff.

I checked the repo and a number of tests as well as the sample fail because they don't have the sockets-for-pcl package installed. You should add those changes to your PR, and if you end up helping with the .nuspec ensure that rda.SocketsForPCL is listed as a dependency. With the compression code removed, I saw that those tests are also failing, which might be a blocker on getting your pull merged. 

Once esskar takes the PR and you get a nuget package up, check the Xamarin forums - I have seen people there asking about PCL-friendly websocket options from time to time. I'll keep it in mind too. :+1:

**Comment by NVentimiglia** [comment]
> I checked the repo and a number of tests as well as the sample fail because they don't have the sockets-for-pcl package installed

Is there a special step for installing this ? I loaded SockersForPCL via nuget,  I figured that was enough.

> With the compression code removed

Yeah, the only thing using the compression was the tests (none of the implementations) so I commented it out. I was overly caffeinated and was up to migrating a .net 3.5 stream to a .net 4.5 stream.

**Comment by rdavisau** [comment]
Yeah - sockets-for-pcl works because it uses the [bait and switch method](http://log.paulbetts.org/the-bait-and-switch-pcl-trick/), so it needs to be installed into your platform projects too, not just the core project. When you install it into a platform project, NuGet picks the best matching assembly from the package and it ends up referencing the native platform implementation. If it's not installed in your platform project, the PCL assembly will be called at runtime, which is just [empty stubs](https://github.com/rdavisau/sockets-for-pcl/blob/master/Sockets/Sockets.Plugin/TcpSocketClient.cs). You can use the 'Manage NuGet Packages for Solution' option in VS to easily add it to multiple projects at once. 

Re: compression code - Cool, I was wondering where it had been used previously, guess it wasn't at all!

**Comment by NVentimiglia** [comment]
I think everything is good now.

https://www.nuget.org/packages/WebSocket.Portable.Core/

**Comment by rdavisau** [comment]
Great!
<sub>By the way, the NuGet description says it's Profile 78 but it's actually [Profile 259](https://github.com/NVentimiglia/WebSocket.Portable/blob/master/WebSocket.Portable.Core/WebSocket.Portable.Core.csproj#L14) (a good thing).</sub>
