### ISSUE TITLE
Potential for missed reads ?

### ISSUE THREAD

**Issue by NVentimiglia** [rdavisau/sockets-for-pcl#20]
Disclaimer : This bug is hard to replicate and may very well be in my websocket.portable library. I`m not sure and any advice would be appreciated.

I am working with a socket server which sends a message on connect. Sometimes the message is not received by the client. My guess is that this is due to receiving logic not  being initialized until after connection. 

Starting with my code, I found an issue here :

https://github.com/NVentimiglia/WebSocket.Portable/blob/master/WebSocket.Portable.Core/_Abstract/WebSocketClientBase.cs#L89

I noticed that the receiving loop was starting after connection. I have since moved my receive loop to happen before opening the client. This did no help.

Next I went backwards to my TCPConnection, I noticed that my read/write streams were not set until after connection. 

https://github.com/NVentimiglia/WebSocket.Portable/blob/master/WebSocket.Portable.Core/_Implementation/TcpConnection.cs#L57

I tried moving the stream referencing to occur before connect, but that left with a null reference exception.

Moving backwards again, I decided to compare the TCPSocketClients in this library. I noticed that the .NET implementation waits for the backing TCPClient to connect before referring the streams where as the WinRT references the streams before the connection task. Could this be the cause ? Is there any way to reference these streams before connection takes place ?

https://github.com/rdavisau/sockets-for-pcl/blob/master/Sockets/Sockets.Implementation.NET/TcpSocketClient.cs#L44

vs

https://github.com/rdavisau/sockets-for-pcl/blob/master/Sockets/Sockets.Implementation.WinRT/TcpSocketClient.cs#L69

**Comment by rdavisau** [comment]
Howdy, I took a quick look into this earlier this morning. 

Regarding the `TcpSocketClient` implementations, you'll see that the stream is only explicitly set if you have `secure:true` in your `ConnectAsync` call, which you aren't doing in Websocket.Portable. Anyway, as long as you `await` the `ConnectAsync` call, it will effectively be atomic to the caller. The .NET and WinRT implementations are equal from a stream perspective in that outside of the `secure` situation, they are resolved in the `ReadStream` and `WriteStream` getters - that is, when you access `client.ReadStream`, `TcpSocketClient` then goes to access the stream property of the underlying platform socket. If you do that prior to connecting, it will probably be `null`, so that would explain the `NRE` you got. I would suggest following the same approach in Websocket.Portable (that is, use a property with a getter that calls into `TcpSocketClient`'s `ReadStream`/`WriteStream` property), though I don't think that will neccessarily solve the problem. 

Re: timing of starting the receive loop etc. - I don't think it would be the cause - it's OK to not read from the stream immediately. If messages are sent to the socket and you're not reading from the stream, they are buffered by the system somehow, so if you wait 10 seconds before calling `Read..`, all the data that had been sent to the socket will come back immediately.

Looking at your `ReceiveLoop` method, I see the looped instructions are wrapped in a `try/catch` which is fine, and that errors are passed to the error handler and logging handled by the log manager. Have you set an error handler and added a receiver to the `LogManager`? You might see an error or some debug information that helps you work out what is causing missed messages. Otherwise, if you have a repro you can share, I can have a look and see if I can help work it out.

**Comment by rdavisau** [comment]
(oops accidentally clicked close)

**Comment by NVentimiglia** [comment]
>Getter setter

Done.

> Buffer

Ok, I just tested and confirmed this. This throws my entire theory out the window. I am going to leave this open for now as I continue my tests. A repo might be the next step. Thanks again.

**Comment by NVentimiglia** [comment]
Found my problem. I was using a StringReader to read the websocket header. When It came time to read the initial 'open' message the regular binary reader would sometimes stop (1 / 200 trys). My guess is the StringReader was corrupting my Read stream (reading a byte too many ?). In any case, I wrote my own string reader method and the issue went away. 

That was a weird one. Thanks for your help.

**Comment by rdavisau** [comment]
Cool, glad you got it sorted!
