### ISSUE TITLE
Windows Store App 8.1

### ISSUE THREAD

**Issue by NVentimiglia** [rdavisau/sockets-for-pcl#23]
Hi again, ran into an issue with a windows store 8.1 project. Here is my exception :

> Could not load file or assembly 'Sockets.Plugin, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The bound assembly has a version that is lower than that of the request. (Exception from HRESULT: 0x80132000)":"Sockets.Plugin, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null

I then updated the plugin to version 1.2, and now 

"The empty PCL implementation for Sockets was loaded. Ensure you have added the Sockets nuget package to each of your platform projects."

Here is my code so you can get a taste of what I am attempting.

`````
  public MainPage()
        {
            this.InitializeComponent();
            Init();
        }

        async void Init()
        {
            try
            {
                Client = new WebSocketClient();
                Client.MessageReceived += OnMessage;
                await Client.OpenAsync("ws://echo.websocket.org");
                await Client.SendAsync("Hello");
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
            }
        }

        private void OnMessage(IWebSocketMessage obj)
        { }
`````

**Comment by rdavisau** [comment]
Howdy,

Just to confirm - 

* First, you added Websocket.Portable to both core and platform projects, and you got the first error
* Then you updated sockets-for-pcl manually (that may not be a good idea, not sure), and got the second error? Did you update in both projects? 

Assuming this is pretty much a bare bones project, are you able to share?

**Comment by NVentimiglia** [comment]
Yes on both counts.

https://github.com/NVentimiglia/WebSocket.Portable/tree/WSA_Example

**Comment by rdavisau** [comment]
Alright, I'll see if I can take a look tonight :+1:

**Comment by rdavisau** [comment]
I took a look, the issue should be the direct project reference to `Websocket.Portable.Core` from your sample app. 

Even though your sample app can obviously reference the main websocket project because they live in the same solution, it needs to be treated like any other real app and use Websocket.Portable through the NuGet package. By referencing it directly, you cut out all the bait/switch magic and whatever happens from there on is probably going to be Bad. Keep in mind, you don't need to worry about specifically installing sockets-for-pcl in a project that you install Websocket.Portable into, because sockets-for-pcl is listed as a dependency in the nuspec and that gets handled automagically. 

I expect if you do the below, it will work:

- Uninstall `sockets-for-pcl` from the WSA app
- Delete the reference to your `Websocket.Portable.Core` project in the WSA app
- Install `Websocket.Portable` into the WSA app; this will install `sockets-for-pcl` too
- Build, run, celebrate :tada: 

Let me know how you go.

**Comment by nfplay** [comment]
Hi, first of all thank you both. This issue reported by @NVentimiglia arose from an investigation of another issue that i am having regarding Windows Store Apps and Realtime.Co Portable Messaging Framework (that uses Websockets).

I too had the first error - "The bound assembly has a version that is lower than that of the request.." - and i too replaced the 1.1.70 assembly version with a correct one (this was itself another issue reported to @rdavisau ). I had the second issue too - "The empty PCL implementation for Sockets was loaded" - and it makes sense, since i probably added the PCL version, which is, like @rdavisau said only a "bait", a placeholder for each platform implementation - and after i got this corrected, i still have a problem, which i described to @NVentimiglia earlier:

"I have a Cocossharp Solution with a shared project where exactly the same code is used to perform Connection and Subscription to Realtime.co both in Windows Phone 8.0 and Windows Store (Windows 8.1). In Windows Phone 8.0 i managed to Connect, Subscribe, Send messages, etc. But in the Windows Store project, even the first Connect fails, after a certain time, with an exception "Websocket has encountered an error".

I added both "Internet (Client & Server)" and "Private Networks (Client & Server)" capabilities in the app manifest; disabled Windows Firewall just in case, nothing worked."

This error: ""Websocket has encountered an error" after a simple connection to Realtime.Co service is the one i'm after, and i dont think it will be solved by these current issues. 

@rdavisau: are you aware of anything specific regarding Windows Store apps that can be interfering with a normal websockets behaviour?

Thanks once again!

**Comment by NVentimiglia** [comment]
@rdavisau 

- Removed rda.Sockets
- Removed direct reference
- Added Websocket.Portable via nuget

Got this error when I tried to connect

> Could not load file or assembly 'Sockets.Plugin, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The bound assembly has a version that is lower than that of the request. (Exception from HRESULT: 0x80132000)":"Sockets.Plugin, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null

- Updated rda.Sockets via nuget

Would no longer throw an exception, but, would stop running. It would never complete connect. Is there any way I could reference my other project directly for better debugging ?

**Comment by NVentimiglia** [comment]
@nfplay 

I think the root of this issue is demonstrated in my simple websocket.portable example application. Once we get the example project working on WSA, everything should work fine.

**Comment by NVentimiglia** [comment]
@rdavisau 

I did a little more investigation on the never ending method.

My plugin stops working when I try to ReadByte() on the handshake.

https://github.com/NVentimiglia/WebSocket.Portable/blob/master/WebSocket.Portable.Core/_Implementation/TcpConnection.cs#L78

I tried replacing this method with a stream reader but no change. (The stream reader was taken out because it sometimes would over-read, causing a scenario very similar to this one).

**Comment by rdavisau** [comment]
I will take a look - it's definitely possible to debug/step through code in your NuGet package, I think the main requirements are that your source/binary are consistent (that is, the binary was built with the source you have on hand) and that you have your debugging symbols too. 

I will check how you go about it tonight but in case you're looking at things now, you might try to turn on first chance exceptions and see if something is being missed there.

**Comment by NVentimiglia** [comment]
Ok awesome. I will be out until tuesday. I dive back in then.

**Comment by rdavisau** [comment]
So I created a new Windows Store app and installed WebSocket.Portable, then added the code from your WSA_Example project. There were no typeload exceptions, so I think the issue you had before would be related to some lingering bad references in the .csproj file. Just installing WebSocket.Portable directly works, no need to fiddle with sockets-for-pcl stuff. As for the example, I sees that it never comes back from the Connect call, as you described above. 

For whatever reason, I can't get WebSocket.Portable to build at the moment, having issues with package restore etc. Once you have built it, you should be able to follow [this](http://stackoverflow.com/a/654711) to enable stepping into the WebSocket.Portable code which should make things a lot easier!

**Comment by rdavisau** [comment]
@NVentimiglia - did you end up getting any further with this?

**Comment by NVentimiglia** [comment]
Got distracted, my last attempt failed. I will try again sunday.

**Comment by NVentimiglia** [comment]
Still no success. I have uploaded a windows universal application and it fails connecting to echo.websockets.org. No exceptions. I have tried loading in the Sockets.Plugin modual and disabled "Just My Code". Here is a sample app.

https://github.com/NVentimiglia/WebSocket.Portable/tree/master/Examples/WebSocket.Universal/WebSocket.Universal

**Comment by lopper** [comment]
@NVentimiglia I looked at your sample. The address parameter you pass into ConnectAsync should be "echo.websocket.org" instead of "ws://echo.websocket.org". This bug is causing your code to hang.

**Comment by NVentimiglia** [comment]
Thanks, I confirmed that it now connects. However whenever I try to read a byte it hangs. No exception is raised.

      private async Task TestRda()
        {
            var socket = new Sockets.Plugin.TcpSocketClient();

            await socket.ConnectAsync("echo.websocket.org", 80, false);

            //Never Ending
            var b = socket.ReadStream.ReadByte();

            Debug.WriteLine("TestRda");
        }

**Comment by lopper** [comment]
@NVentimiglia I've debugged into this issue. I found that there is a problem with the sockets-for-pcl library within the ConnectAsync call. 

`
   return _backingStreamSocket
                        .ConnectAsync(hn, sn, spl)
                        .AsTask().WrapNativeSocketExceptions();
`

if you change the above statement to:

'
   return _backingStreamSocket
                        .ConnectAsync(hn, sn, spl)
                        .AsTask()
'
it should fix your issue.  I have not looked into the reason why WrapNativeSocketExceptions() causes this issue. If you find know, please share.

**Comment by NVentimiglia** [comment]
Ok, right on. When do you expect to have a patch ?

https://github.com/rdavisau/sockets-for-pcl/blob/master/Sockets/Sockets.Implementation.WinRT/TcpSocketClient.cs#L63

**Comment by lopper** [comment]
@rdavisau do you know why WrapNativeSocketExceptions() would cause an issue with ConnectAsync

**Comment by NVentimiglia** [comment]
This is conjecture, but maybe the await is being associated with the wrapping task and not the connect task.  A cold task if you will. 

http://stackoverflow.com/questions/24237266/why-awaiting-cold-task-does-not-throw

Try this ? Or something like this.

       public Task ConnectAsync(string address, int port, bool secure = false)
        {
            var hn = new HostName(address);
            var sn = port.ToString();
            var spl = secure ? _secureSocketProtectionLevel : SocketProtectionLevel.PlainSocket;

            return _backingStreamSocket
                        .ConnectAsync(hn, sn, spl)
                        .WrapNativeSocketExceptions()
                        .AsTask();
        }

or even a old school try / catch.

Reading MSDN 

https://msdn.microsoft.com/en-us/library/vstudio/ms229049(v=vs.100).aspx

>  This practice should be used only in situations where the original exception is not meaningful to the person who receives the exception, or the call stack for the exception is misleading or uninteresting

I wouldn't mind the native exception message.

**Comment by rdavisau** [comment]
@lopper thanks for getting involved!

Actually there is a bunch of WIP stuff in `master` right now, including the native exception code, that is not in the current shipped version of sockets-for-pcl. Indeed, `WrapNativeSocketExceptions` is breaking pretty much every WinRT test right now. Assuming you are using the Nuget package Nick, that stuff isn't relevant to this issue. 

In order to debug against the 1.2.1 code you would need to roll back to 31bcd81163f9cf74a73a859e8a0283b716916e3d I believe.

`ReadByte` is a stream method, it will block until there is a byte available to read; I'm not familiar with the ws protocol but in your example do you need to send any data to the remote server in order to initiate the handshake?

Just to cover the reasoning behind `WrapNativeSocketExceptions`, the purpose is to allow you to specifically catch socket related exceptions from the PCL. In WinRT they are all `Exceptions` with `HResult`s anyway, but in .NET they are `SocketException`, which is not available in a PCL. The method wraps socket exceptions in a PCL socket exception provided by the library so that you can catch that type of exception specifically, from PCL code.

**Comment by NVentimiglia** [comment]
>  Actually there is a bunch of WIP stuff in master right now, including the native exception code, that is not in the current shipped version of sockets-for-pcl

Ooh ok. Hmmm I would prefer to use the latest, when do you expect to have a RC ?

>  I'm not familiar with the ws protocol but in your example do you need to send any data to the remote server in order to initiate the handshake?

Yes, I am sending a handshake.

https://github.com/NVentimiglia/WebSocket.Portable/blob/master/WebSocket.Portable/WebSocket.Portable/_Abstract/WebSocketBase.cs#L143

        private async Task TestRda()
        {
            var socket = new Sockets.Plugin.TcpSocketClient();

            await socket.ConnectAsync("echo.websocket.org", 80, false);

            // Send HS
            var handshake = "GET / HTTP/1.1\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Version: 13\r\nSec-WebSocket-Key: p2z/MFplfpRzjsVywqRQTg==\r\nHost: echo.websocket.org\r\nOrigin: http://echo.websocket.org/\r\n\r\n";
            var bytes = UTF8Encoding.UTF8.GetBytes(handshake);
            await socket.WriteStream.WriteAsync(bytes, 0, bytes.Length);
           
            // Read HS, Never Ending
            var b = socket.ReadStream.ReadByte();

            Debug.WriteLine("TestRda");
        }

**Comment by rdavisau** [comment]
Probably another week for the next version. 1.2.1 is easily the preferred and stable right now. Thanks for updating the test - I will have a bit of a play with that.

**Comment by rdavisau** [comment]
OK, I identified the issue. It is related to #18 / #19, and caused by the fact that without specifying a buffer size when getting a reference to a stream in WinRT, you get a buffered stream with a large buffer size; whereas on .NET the stream is unbuffered by default.

If you call `FlushAsync` after your `await socket.WriteStream.WriteAsync(bytes, 0, bytes.Length);` line, you will see that `ReadByte` returns - the issue therefore is that the 'sent data' is buffered by the OS and not sent along (if enough additional data was 'written', it would eventually shuttle it all across). Obviously with Android/iOS being .NET, their streams were already unbuffered so the data is sent instantly. 

The workaround is to make a `FlushAsync` call; but this was addressed as part of #19 which will be in the next release - by default, WinRT sockets willl be unbuffered and you will also have the ability to specify a buffer size if you wish.

**Comment by rdavisau** [comment]
@NVentimiglia @lopper 

1.2.2 is finally on NuGet with the ability to specify write buffering and consistent buffering between .NET and WinRT. The default is unbuffered - standard .NET behaviour - and I have verified that the above code fragment works as expected in a windows store app. Apologies for the delay and let me know how you go!

**Comment by NVentimiglia** [comment]
@rdavisau  Cool ! Ill double check tonight.

**Comment by NVentimiglia** [comment]
Works on my end, thanks again.
