### ISSUE TITLE
Listening terminates program

### ISSUE THREAD

**Issue by janniksam** [rdavisau/sockets-for-pcl#40]
Okay, here is a very short console app which is terminating after StartListeningAsync()... Do you know, what could be the problem?

    class Program
    {
        static void Main()
        {
            var p = new Program();
            p.Start();
        }

        private async void Start()
        {
            var server = new Server();
            await server.Start();
            Console.WriteLine("... Server started");
            while (true)
            {
                Thread.Sleep(100);
            }
        }
    }

    public class Server
    {
        public async Task Start()
        {
            var listenPort = 11000;
            var listener = new TcpSocketListener();

            // when we get connections, read bytes until we get -1 (eof)
            listener.ConnectionReceived += async (sender, args) =>
            {
                var client = args.SocketClient;

                while (true)
                {
                    // read from the 'ReadStream' property of the socket client to receive data
                    var nextByte = await Task.Run(() => client.ReadStream.ReadByte());
                    Debug.Write(nextByte);
                }
            };

            // bind to the listen port across all interfaces
            await listener.StartListeningAsync(listenPort);
        }
    }

**Comment by rdavisau** [comment]
Hello and apologies for the delay in responding -

Your code for the `Server` class looks fine to me, I think that it may not actually be terminating at `StartListeningAsync()`. Rather, because you are not `await`ing `p.Start()`, the execution of `Main()` continues immediately* after the call to `p.Start()`, therefore finishing and tearing down the application. The IDE is probably giving a warning to this effect. It might be useful to read up a little on `async`/`await` to help understand why this is the case. 

A quick fix will be to change `Program.Start()` from `async void` to `async Task`, then in `Main()` you should be able to call `p.Start().Wait()`, to ensure the program doesn't terminate early. That is not code we would normally write in a non-console situation, but I think it is OK here because of the different threading mechanism of the console. If you do hit a deadlock (nothing happens later when you expect it to), you could change your code to `Task.Run(()=> p.Start()).Wait()`. Again, if you read up on `async` it will be helpful here. 

Please re-open if this didn't solve your problem. I will respond to the sockethelpers question shortly!
