### ISSUE TITLE
DataAvailable

### ISSUE THREAD

**Issue by vbisbest** [rdavisau/sockets-for-pcl#44]
Is there a way to tell if there is data available on a socket stream?  I am looking for something like DataAvailable on a NetworkStream.

Thanks

**Comment by rdavisau** [comment]
Hi there. Take a look at #24 - unfortunately we can't use `DataAvailable` because there doesn't seem to be any equivalent in WinRT.

However, you could possibly use this [BetterTcpSocket](https://gist.github.com/rdavisau/7b466c855118a00c901a) I once put together (see #9 for discussion/context - it was designed to proactively read from the socket and buffer data in order to immediately detect disconnection), and add an additional property that checks whether the `BlockingMemoryStream` has any data in the buffer. In that case, the socket would still be being read immediately in the background, but you would be able to check whether data was available before your made a call to `Read` in your own code. It might be what you're looking for?

**Comment by vbisbest** [comment]
Thank you for your response.  Great approach you you have with BetterTcpSocket.   Another question unrelated since you are up to speed on this socket stuff.  Are you familiar with any DNS solutions that are PCL?   I need the ability to resolve a host name and do a service record (SRV) look up.   THanks!

**Comment by vbisbest** [comment]
Also, it seems that is only a partial class (BetterTCPSocket).  Missing the using statements and some other issues.  Do you have a full example?

**Comment by rdavisau** [comment]
Hey again,

I'm not really familiar with anything DNS that is also PCL compatible. If you only need to do DNS lookup, you might try implementing it yourself using sockets-for-pcl (I think it's just the one request/response), or adapt an existing C# DNS library to use sockets-for-pcl instead (that is, switching out the socket used by the library with a tcp or udp socket from sockets-for-pcl). 

As for `BetterTcpSocketClient`, I copied it into a new PCL with sockets-for-pcl installed and Resharper offered to add the following usings: 

```
using System;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Sockets.Plugin;
using Sockets.Plugin.Abstractions;
```

With those you should be good to go!
