### ISSUE TITLE
Should this work on MVC?

### ISSUE THREAD

**Issue by cskardon** [rdavisau/sockets-for-pcl#73]
So this is just a question, not an issue as such.

If I create a PCL project that wraps connection to/from a socket, and reference this in a console app, all good, everything works as expected. When I reference it into an MVC web app, when I:

`await socket.ConnectAsync("localhost", 9988);`

The debugger hits that line and then sort of disappears, so quick question - should it work in MVC?

I have (I presume naively) worked on the principle that as MVC is using net45x it would have access to the same sockets that my console app has access to....

Erm, thanks

Chris

**Comment by rdavisau** [comment]
Howdy, 

I can't say that I've tried it, but I don't see why not :star2:.

Usually the debugger just disappearing after an `async`-y line like that means:

- that statement threw, but for whatever reason the exception was absorbed into the darkness (may be related to your method signature, or the way the caller invoked the method, or debugger having a bad day) 
- that statement really is still executing

A connection to `localhost` probably isn't going to take a long time - it should succeed or fail instantly - so I'm leaning towards the former. You could try wrapping the statement in a `try`/`catch` block and putting a breakpoint inside the catch clause to see whether an exception is being thrown. Otherwise you could set the debugger to break on thrown exceptions, rather than unhandled. Apologies if any of this is obvious/you've tried it.

Let me know how you go!

**Comment by cskardon** [comment]
Heh, obvious is fine :)  thank you for responding at all!

I've tried the try/catch routine, and can make it hit there by putting something like a huge port number in, so I know it _will_ catch the exception if it is thrown, but it never gets there, nor the line after the connection attempt.

Hmmmm.....

**Comment by rdavisau** [comment]
Strange.. 

- can you check whether something simpler like `var ifs = await CommsInterface.GetAllInterfacesAsync();` returns? 
- just because we're stabbing in the dark, might be worth trying both of `socket.ConnectAsync("localhost", 9988).Wait();` and `await Task.Run(() => socket.ConnectAsync("localhost", 9988));`, to see if anything happens in either case.

**Comment by cskardon** [comment]
Interesting - 

`Task.Run(() => socket.ConnectAsync("localhost", 9988).Wait(); works, where `socket.ConnectAsync("localhost", 9988).Wait()` doesn't....

**Comment by rdavisau** [comment]
Hmm, so it feels like an `async`y thing.. Might be worth sharing the signature of the method that the call is in, and how the method is being called?

**Comment by cskardon** [comment]
So, whole thing like this:

```
public ActionResult SyncAction() {
    var task = GetConnectionAsync();
    task.Wait();
}

private async Task GetConnectionAsync() {
    var socketClient = new TcpSocketClient();
    await socketClient.ConnectAsync("localhost", 9988);
    socketClient.WriteStream.SendByte(1);
}
```

Debug wise - it will go into the `GetConnectionAsync` method, hit the `ConnectAsync` bit and then just disappear.

If the call in the `SyncAction` is changed to `var task = Task.Run(() => GetConnectionAsync());` all works as expected...

**Comment by rdavisau** [comment]
Ah - it's a deadlock. It's beyond me right now to explain in detail why, but essentially `task.Wait()` blocks the context that `ConnectAsync` needs to return to after it completes. When you wrap the call in `Task.Run`, `ConnectAsync` begins in whatever context `Task.Run` gives it, and it can return to that when done because it is not blocked.

Wrapping the call in `Task.Run` is a reasonable approach if you can't change the outer signature be return `Task<ActionResult>`. MVC is not an area I know much about, so I'm not sure!

**Comment by cskardon** [comment]
That's awesomeballs, thanks for the help getting through it!

**Comment by cskardon** [comment]
I'll close this now then :)

**Comment by rdavisau** [comment]
Glad we sorted it out! :+1:
