### ISSUE TITLE
TcpSocketClient & Windows 10

### ISSUE THREAD

**Issue by bvenhaus** [rdavisau/sockets-for-pcl#79]
The default constructor for the TcpSocketClient class will not work with Windows 10 apps when compiled to native.  For those I found that the buffer size needs to be greater than 0.  If no buffer size is specified you may want to use the default value of 16,384 bytes.  Oddly enough, this doesn't seem to be an issue for debug builds that aren't compiled to native.

**Comment by rdavisau** [comment]
Interesting find - what happens when the buffer size is 0? Does it not work or does it throw an error?

When we added the buffer size support we had to decide between defaulting to the default for .NET (0) and the default for WinRT (16,384), I went with .NET as I figured the majority of users were likely to expect that behaviour. But if 0 is unsupported on win10 then that is not going to fly .. :chart_with_downwards_trend: Changing the default buffer size would have to be considered a breaking change I think - I'll have to sneak it into the 2.0 release.

**Comment by bvenhaus** [comment]
Sorry, but my issue probably doesn't warrant a change to your library.  No exceptions are thrown.  The issue actually appears to be related to my code & Windows 10 handling of the Flush method.  After a write to the OutputStream my code is calling Flush.  For native builds this will block indefinitely when the buffer is 0. For normal builds it doesn't block & continues to the next line of code. The call to Flush the buffer when the buffer size is 0 probably doesn't make a whole lot of sense. I removed the Flush call & everything works fine. You can go ahead & close this issue.  Because it takes so long to compile to native I tend to make assumptions.

**Comment by rdavisau** [comment]
Ok, fair enough - I think you are right and that the difference in behavior is a platform issue - whether or not it makes sense to call Flush with a zero buffer, I don't think it makes sense for it to block!

**Comment by bvenhaus** [comment]
Lol, agreed.
