### ISSUE TITLE
TCP - Write/Read async example

### ISSUE THREAD

**Issue by Emixam23** [rdavisau/sockets-for-pcl#88]
Hi,

I'm trying to use your package from a personal PCL. (To not duplicate code over each page of my app)
However, I'm sure how to use it...

My PCL is a SingleTown class (Only one class instantiated for all of my program)

        public class TCPclient
        {
        private TcpSocketClient client;
        public string server_ip { get; set; }
        public int port { get; set; }

        #region /// Constructors
        public TCPclient()
        {
            client = new TcpSocketClient();
            server_ip = "";
            port = 0;
        }

        public TCPclient(string server_ip, int port)
        {
            client = new TcpSocketClient();
            this.server_ip = server_ip;
            this.port = port;
        }
        #endregion

        #region /// Messaging part
        private class DialMessageContainer
        {
            public string Type { get; set; }
            public JToken Content { get; set; }

            public static string Serialize(DialMessageContainer message)
            {
                return JToken.FromObject(message).ToString();
            }
        }

        public async void send<T>(string type, T value)
        {
            try
            {
                DialMessageContainer message = new DialMessageContainer { Type = type, Content = JToken.FromObject(value) };
                string data = DialMessageContainer.Serialize(message);

                // convert data of string into a byte array
                byte[] bytes = new byte[data.Length * sizeof(char)];
                Buffer.BlockCopy(data.ToCharArray(), 0, bytes, 0, bytes.Length);

                client.WriteStream.Write(bytes, 0, 1024);
                await client.WriteStream.FlushAsync();
            }
            catch (Exception e)
            {
                System.Diagnostics.Debug.WriteLine(e.ToString());
            }
        }
        #region /// Dialog class
        public class DialAuthentication
        {
            public string UUID { get; set; }
        }
        public class DialRegistrationAsAvailable
        {
            public string Location { get; set; }
        }
        #endregion
        #endregion

        #region /// Connection/Disconnection
        public async void connect()
        {
            await client.ConnectAsync(this.server_ip, this.port);
        }

        public async void disconnect()
        {
            await client.DisconnectAsync();
        }
        #endregion

        #region /// Singletown part
        private static TCPclient instance = null;

        public static TCPclient getTCPClient()
        {
            if (instance == null)
            {
                instance = new TCPclient();
            }
            return (instance);
        }

        public static void setTCPInstance(TCPclient tcpclient)
        {
            instance = tcpclient;
        }
        #endregion

The throwed exception is "A method was called at an unexpected time. (Exception from HRESULT: 0x8000000E)". I think I have an error about writing, because unlike your sample, I'm writing data from a class object. Moreover, I don't understand how can I readAsync(). Does I have to read byte by byte? How to call a function after a message data is received? how to handle data?..

Thank for help !

**Comment by rdavisau** [comment]
Ok, I've had a look at your code and your question - apologies as what I posted in the other issue does not help here. 

`A method was called at an unexpected time` sounds like a WinRT/UWP exception. As the message suggests, it means that socket methods were not called in the order that WinRT would like them to be called. 

Looking at your code, the general structure looks fine and makes sense. So, my hypothesis is that your `send` method is being called while the socket is not connected. I think that maybe your `connect` method is failing, but that is being hidden by the fact that your methods are all `async void`, rather than `async Task`. [Here](https://msdn.microsoft.com/en-us/magazine/jj991977.aspx) is an article that discusses why `async void` should not be used except in event handlers. I think that if you change your methods to `async Task` you'll be able to get more information about what is going on. Of course, all the code calling in to your `connect` and `send` methods must `await` those calls, and their signatures should be `Task` or `Task<T>` etc. etc. etc. As they say - "async all the way" 📈 

Let me know how things go with the modified code!

**Comment by Emixam23** [comment]
Here is what I'm trying to test:

        try {
                TCPclient tcp = new TCPclient()
                {
                    server_ip = "xxx.xxx.xxx.xxx",
                    port = XXXX,
                };
                await tcp.connect();
                TCPclient.setTCPInstance(tcp);

                DialAuthentication auth = new DialAuthentication()
                {
                    UUID = "A_ENCODED_TOKEN_AS_STRING",
                };
                tcp.send("Authentication", auth);
            } catch (Exception e)
            {
                System.Diagnostics.Debug.WriteLine(e.ToString());
            }

I edited connect() and send<>()

        // Connect
        public async Task connect()
        {
            try {
                await client.ConnectAsync(this.server_ip, this.port);
            }
            catch (Exception e)
            {
                Debug.WriteLine("Connection failed:" + e.ToString());
            }
            finally
            {
                Debug.WriteLine("Get the hell out!");
            }
        }

        // Send
        public async void send<T>(string type, T value)
        {
            DialMessageContainer message = new DialMessageContainer { Type = type, Content = JToken.FromObject(value) };
            string data = DialMessageContainer.Serialize(message);

            Debug.WriteLine(data);

            // convert data of string into a byte array
            byte[] bArray = GetBytes(data);

            try
            {
                await client.WriteStream.WriteAsync(bArray, 0, bArray.Length);
                await client.WriteStream.FlushAsync();
            }
            catch (Exception e)
            {
                Debug.WriteLine(e.ToString());
            }
        }

        static byte[] GetBytes(string str)
        {
            byte[] bytes = new byte[str.Length * sizeof(char)];
            Buffer.BlockCopy(str.ToCharArray(), 0, bytes, 0, bytes.Length);
            return bytes;
        }

How can I know if the connection is ok?

**Comment by Emixam23** [comment]
Omg... You're right.. I can't connect that's the problem.. I didn't realize because I tried with a TCP client from my Windows10 machine (which running Ubuntu (which contain my server) on VMWare)
So with the phone you said it could be the client which isn't connected and that was it ! I tried with another of my computer to access this server (from Ubuntu host by VMware on the first computer) and it didn't work as well... ;)

**Comment by rdavisau** [comment]
Yeah - getting from an emulator to a VM can be difficult because of interface configurations, firewalls, NAT etc. 
If you are running windows and ubuntu is in the VM, you could use ssh (via putty for example) to forward a port on your windows machine to the server on the ubuntu VM, then the phone would only need to connect to the local windows machine.

If you are not seeing the connection error, then your outer `async` code (not shown in your examples) may still not be correct. Otherwise, it could just be waiting at the `connect` if one of the firewalls is dropping your connection attempt (as opposed to rejecting it, which would result in a connection refused exception).

**Comment by Emixam23** [comment]
I can connect() now ;) However something seems weird.. Every message are only sent when I close de socket.. I mean, I stop running my app from Visual Studio and then, each message comes up in my server

**Comment by Emixam23** [comment]
I can connect() now ;)

**Comment by Emixam23** [comment]
I'm able to send message, it does works :) However  I'm getting something strange.. I don't think it's coming from your package but I ask about this issue on [Stackoverflow](http://stackoverflow.com/questions/37617278/xamarin-golang-invalid-character-x00-looking-for-beginning-of-objec/37617710#37617710). I still don't understand how to use your package to read.. I want for each incoming message make something like that

`client.reader() => async HandleMessage(string message) { /* code */}`

Sorry I don't really know how to write my idea better.

I hope it possible, thank for help !

**Comment by Emixam23** [comment]
IMPORTANT:

Note that my code is sending (**signed bytes**). It may causes problems if the other side works with (**no-signed bytes**).

**Comment by rdavisau** [comment]
^ sounds like it's all sorted now!
