### ISSUE TITLE
Read stream

### ISSUE THREAD

**Issue by galex66** [rdavisau/sockets-for-pcl#9]
Thanks for the plugin!
I must implement a client TCP/IP that needs to read on a socket while the socket is working.
I put the reading cycle on a separate thread and I use the block method ReadStrem.Read with set the readtimeout, but I can't known if exit by timeout or because the socket is closed.
Ideally the Readstream.Read is blocking indefinitely and exit only if socket is closed.

Anothe question:
If the server called close the socket or socket is pending status,I don't have any event that signals me .

Can you help me?

**Comment by rdavisau** [comment]
Hi!

From what I understand, you want to be able to wait indefinitely for a read. I believe that by default, `ReadStream` has a timeout of `-1` aka `Timeout.Infinite`. So, by default it will block until the connection is dropped or data is received - just dont set a timeout! If you do want to set a timeout, I would recommend using the `async` read methods instead and using a `Task`-based timeout like [this](https://gist.github.com/rdavisau/a3bfa15fc77fbc789c59) - it will throw `TimeoutException` if the timeout is exceeded, otherwise it will return the results of the original task. 

To know if the socket was closed, you can check the return value. If you use `ReadByte`, it returns the single byte that was sent, or `-1` if the stream was closed. If you use `Read` to read to seperate `byte[]` variable, the return value indicates the number of bytes read - if this is `0`, the stream was closed. 

For your second question, knowing that the connection was closed or dropped is actually a relatively difficult/annoying problem! Generally, it is accepted that you cannot trust a socket to be connected without performing a read or write operation from it. There is some useful discussion [here](http://stackoverflow.com/questions/10096462/handling-winrt-streamsocket-disconnects-both-server-and-client-side). Because sockets-for-pcl is quite 'light touch' (i.e. I'm letting you as the developer deal directly with the read/write streams), there isn't really a good point to inject that kind of detection into the code - if you are working directly with the streams, other code written to test connectivity etc. is going to interfere. 

That said, I also have the [sockethelpers](https://github.com/rdavisau/sockethelpers-for-pcl) project that I aim to include that kind of functionality in. The idea is that you defer read/writing from sockets to the library, allowing it to do the connectivity detection itself without worrying messaging operations being mixed up in the middle of it. Right now the connectivity stuff is not complete but it is on my radar for the next few weeks. In the short term, you can implement the suggestions above, longer term I should have something standardised for it :star2: .

**Comment by freever** [comment]
Just chipping in here becos it's an interesting problem. I am new to sockets so it's all unfamiliar terrain. I have also just discovered that writing to my server socket does not fail if the server is disconnected. So I am planning to write a little handshaking step in my connection service that will ping the server with a guid and fail if it doesnt get it pinged back within a timeout period. Does that sound feasible to you? I have node.js on the backend so I'm not sure if your sockethelpers project will help me...

**Comment by rdavisau** [comment]
@freever Thanks for joining the discussion! 

Yes, bouncing messages back and forth is a feasible approach, but I do see a few drawbacks: 

- You don't find out about disconnection until `timeout` occurs - this may or may not be a big deal for your application
- If `timeout` is relatively short, it is more susceptible to network issues - this is unlikely but still possible 
- You might hit complexity co-ordinating your 'true' read/write operations with your 'keepalive' chatter

All that said, if you can handle the last point reliably it should work fine for most applications. It does require you to have control over the other end's code in order to handle the keepalive stuff though, which is a bummer from a library perspective. 

From everything I've seen, I think that riding `ReadStream` is the most reliable and portable way to independently determine you are disconnected. After thinking hard for while, I'm playing with the idea of a version of `TcpSocketClient` that exposes `ReadStream` as an in-memory stream that it feeds by eagerly/constantly reading from the underlying socket stream. In that way, it will always know immediately when the connection is dropped - so can raise a disconnected event - but you as the developer still have the ability to read out data from the exposed `ReadStream` at your own pace. I'll experiment with this idea a bit!

**Comment by rdavisau** [comment]
Ok, I have written an implementation of `ITcpSocketClient` that wraps the standard `TcpSocketClient` but does what I described in the previous message to detect when it has been disconnected. Seems to be working well! I will think about how to bring it into the core library, but for now you can drop [these classes](https://gist.github.com/rdavisau/7b466c855118a00c901a) into your project's PCL and use `BetterTcpSocketClient` wherever you previously used `TcpSocketClient`. 

`BetterTcpSocketClient` is a drop-in replacement, but it is *not* a `TcpSocketClient` subclass. It has `Connected` and `Disconnected` events, as well as an `Errored` event for anything that gets thrown in the middle of the stream reading code. I'm not sure what errors could be thrown from there so that part may need some more thought. 

Let me know how it goes for you guys!

**Comment by freever** [comment]
Thanks Ryan, that looks awesome. I'll try and integrate it with my app and
feedback on how it goes.

**Comment by galex66** [comment]
Thanks Ryan for the help !
It's all right

**Comment by rdavisau** [comment]
Glad it's working for you both! 

There will be a major version bump for sockets-for-pcl in the next couple of weeks - at that point I will replace the current `TcpSocketClient` implementation with one more like `BetterTcpSocketClient`, so you'll get connection monitoring by default. When that happens I'll come back here and let you know so you can switch back to it and be on the main code again :star2:
