### ISSUE TITLE
TCP send string

### ISSUE THREAD

**Issue by JustMeDaFaq** [rdavisau/sockets-for-pcl#92]
Hi, is it somehow possible to send an string instead of just an byte?
Cant get it to work.

**Comment by rdavisau** [comment]
Hi - take a look at the sample [here](https://github.com/rdavisau/sockets-for-pcl/blob/v2.0.0-pre/Sockets/linqpad-samples/Tcp/Strings.linq#L56-L101).

The trick is use a basic protocol that involves preceding each message with the length of the string, so that the receiver knows how long it needs to read for. The methods I linked there are extensions on `TcpSocketClient` so you can call `client.SendString` and `client.ReceiveString` if you control both ends.

Let me know if you need any more help!
